```{r echo=FALSE}
filtered <-
      data %>%
      filter(
        Indicator.Number == input$indicatorInput,
        variable == input$yearInput
      )
    
    newslope <- filter(slopes, Indicator.Number == input$indicatorInput)
    
    #merge state shape data with indicator data
    filtered <- inner_join(filtered, states, by = "Awardee")
```

This graph displays the nationwide trends for `r filtered[1,"Indicator.Name"]` for `r input$yearInput`

```{r fig.width=12, fig.height=8, echo=FALSE}
    
    ggplot(data = filtered) + 
      geom_polygon(data = map_data("state"), aes(x=long, y = lat, fill = value, group = group), fill = "grey", color = "white") +
      geom_polygon(aes(x = long, y = lat, fill = value, group = group), color = "grey40") + 
      scale_fill_gradient2(low = 'white', mid = 'lightblue', high = 'darkblue', name = paste(input$yearInput[1],"Value"), 
                           limits=c(0, max(subset(slopes, Indicator.Number == input$indicatorInput)$value))) +
      geom_point(data = newslope, aes(long, lat, size = (abs(Slope)), color = sign, shape = sign), fill = "white") +
      scale_size(name = "Yearly Change") +
      scale_shape_manual(values=c(25, 24), name = "Trend", labels = c("Getting Better","Getting Worse")) +
      scale_color_manual(values=c("darkgreen", "red"), name = "Trend", labels = c("Getting Better","Getting Worse")) +
      coord_fixed(1.3) +
      theme(axis.line=element_blank(),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks=element_blank(),
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            panel.background=element_blank(),
            panel.border=element_blank(),
            panel.grid.major=element_blank(),
            panel.grid.minor=element_blank(),
            plot.background=element_blank())
    
    
```
